### ISSUE TITLE
quickstart waypoint scan error

### ISSUE THREAD

**Issue by crisman** [SpaceTradersAPI/api-docs#12]
From `/register` with `faction=VOID` the ship I started with was `"nav" { "status": "DOCKED" }`
which caused the example `$apiUrl/my/ships/$shipSymbol/scan/waypoints` to fail like so:

```
{
    "error": {
        "code": 4236,
        "data": {
            "waypointSymbol": "X1-UK8-56510E"
        },
        "message": "Ship action failed. Ship is not currently in orbit at X1-UK8-56510E."
    }
}
```

I can see two options:
 - Update quickstart to have an `/orbit` call
 - Create command ships already in orbit

**Comment by thebrubaker** [comment]
This should be fixed now with the update to the docs!
