### ISSUE TITLE
/my/ships/{shipSymbol}/scan/waypoints endpoint missing in SpaceTraders.json

### ISSUE THREAD

**Issue by crisman** [SpaceTradersAPI/api-docs#16]
The ship scan endpoint used in `quickstart.md` (`https -A bearer -a $apiToken POST $apiUrl/my/ships/$shipSymbol/scan/waypoints`) does not appear in the API doc `SpaceTraders.json`.

On the v2.api running server there is an enpoint at `/my/ships/{shipSymbol}/scan/systems` that does return data and start a cooldown on the ship, so it does seem to exist.

Please update `SpaceTraders.json` with information on that endpoint.

**Comment by space-admiral** [comment]
Thanks! Updated with the scan waypoints endpoint.
