### ISSUE TITLE
Missing instructions for getting the location in the quickstart

### ISSUE THREAD

**Issue by LucaJunge** [SpaceTradersAPI/api-docs#22]
I was just trying out to get the location of my headquarters and the corresponding system and was stuck for quite a while on the "View your starting location" step.

It is not clear from the previous step that my "headquarters" response from `/my/agent` is a combined string from the system.
For example:

My "headquarters" string is `B0-DT55-202001`, which contains the system BO-DT55 and the waypoint 202001

I would suggest adding a hint in the quickstart that the headquarters response is a concatenated string and you have to separate it for the next query `https://api.spacetraders.io/v2/systems/:systemSymbol/waypoints/:waypointSymbol`

**Comment by mateuscelio** [comment]
I was also stuck on this step. Thanks for clarifying it.

**Comment by space-admiral** [comment]
Awesome this is super helpful, I updated the docs with clarification. Would you mind taking a look at that step and confirming if that helps?

**Comment by LucaJunge** [comment]
Yes, that's a better clarification. Thank you, that makes the onboarding way easier!
