### ISSUE TITLE
Invalid Retry-After headers

### ISSUE THREAD

**Issue by dbeckwith** [SpaceTradersAPI/api-docs#24]
I'm using the Space Traders API in Python with a client generated by openapi-generator. When I hit rate-limit errors, I get an error from the underlying `urllib3` library used for the network handling:
```
urllib3.exceptions.InvalidHeader: Invalid Retry-After header: 0.493
```

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After), the `Retry-After` header value must be either a date string or an _integer_ number of seconds.

**Comment by galdor** [comment]
Correct, see [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110#field.retry-after).
If you need sub-second precision (which is the case here), you have to use a custom header field.

**Comment by space-admiral** [comment]
Ok good to know, I think we'll round this up the the full second so it doesn't break client generators. Really appreciate you catching this!

**Comment by dbeckwith** [comment]
Seems like this has been fixed now?
