### ISSUE TITLE
Error 500 gives a link to a deprecated repository

### ISSUE THREAD

**Issue by nielsegberts** [SpaceTradersAPI/api-docs#31]
When I encountered an error 500, it returned the following message:

```
{
  "error": {
    "code":500,
    "message":"Something unexpected went wrong! If you want to help you can file an issue here: https://github.com/SpaceTradersAPI/issues-and-suggestions"
  }
}
```

However that repository mentions it's deprecated and issues should be filed here instead.

**Comment by space-admiral** [comment]
Thanks for catching this! Just pushed an update for that message.
