### ISSUE TITLE
Refining throws 500 errors

### ISSUE THREAD

**Issue by vsupalov** [SpaceTradersAPI/api-docs#32]
Upon trying to refine a single unit of PLATINUM, the following two responses were seen:

```
{
  "error": {
    "code": 500,
    "message": "Something unexpected went wrong! If you want to help you can file an issue here: https://github.com/SpaceTradersAPI/issues-and-suggestions"
  }
}
```
```
{
  "error": {
    "message": "Failed to update ship cargo. Ship (redacted) cargo does not contain 3 unit(s) of PLATINUM_ORE. Ship has 1 unit(s) of PLATINUM_ORE.",
    "code": 4219,
    "data": {
      "shipSymbol": (redacted),
      "tradeSymbol": "PLATINUM_ORE",
      "cargoUnits": 1,
      "unitsToRemove": 3
    }
  }
}
```

The ship in question has plenty of empty cargo space.

Despite the 500 error, the cooldown seems to be triggered nevertheless:

```
{
  "error": {
    "message": "Ship action is still on cooldown for 24 second(s).",
    "code": 4000,
    "data": {
      "cooldown": {
        "shipSymbol": "(redacted)",
        "totalSeconds": 180,
        "remainingSeconds": 24,
        "expiration": "2023-05-12T13:24:31.213Z"
      }
    }
  }
}
```

**Comment by space-admiral** [comment]
Thanks for bringing these up! In the 500 instance, I think we can improve that so it hopefully wouldn't trigger the cooldown in that scenario. In the Error for your refine request, it looks like you need 3 units of Platinum Ore in your hold, but only had 1 unit of the ore. The request requires 3 ore to refine 1 Platinum (unless of course you had the 3 ore, in which case ping me again so I can see if there is a bug).

Hope that helps!
