### ISSUE TITLE
Docking throws a 500

### ISSUE THREAD

**Issue by wolfadex** [SpaceTradersAPI/api-docs#33]
The endpoint `https://api.spacetraders.io/v2/my/ships/{shipSymbol}/dock` returns
```
{
  "error": {
    "code":500,
    "message":"Something unexpected went wrong! If you want to help you can file an issue here: https://github.com/SpaceTradersAPI/issues-and-suggestions"
  }
}
```

**Comment by space-admiral** [comment]
Thanks for reporting this! I think we had some stability issues for a bit, but should be more stable. Let me know if you see this again or often enough that it could be a larger issue.
