### ISSUE TITLE
[Feature Request ✨] Ability to filter systems by sector

### ISSUE THREAD

**Issue by wolfadex** [SpaceTradersAPI/api-docs#39]
It would be great to be able to query for systems within a particular sector, either through a query param like `sector=X1` or as a separate endpoint like `/v2/sectors` and `/v2/sectors/{sectorSymbol}` where a sector returns an array of System symbols.

**Comment by space-admiral** [comment]
Great suggestion! We only have the one sector right now, but when we add more this is definitely something we want to implement.
