### ISSUE TITLE
Document status endpoint

### ISSUE THREAD

**Issue by pennyarcade** [SpaceTradersAPI/api-docs#43]
https://api.spacetraders.io/v2/ is undocumented.
While you are at it also consider streamlining Leaderboard entries as to use only one DTO for all leaderboards:

class Entry {
   string $agentSymbol;
   int $value;
}

The meaning of $value is derived and directly dependent on the leaderboard type, naming the $value differently for every leaderboard does not add information.

This simplifies leaderboard handling on client side as you can use generic code for everything but the headline.

**Comment by space-admiral** [comment]
Thanks for reporting this! We documented the endpoint in the last reset, let me know what you think. I didn't get to the second half of your suggestion to make it a generic type - we're not sure just yet how the leaderboard is going to evolve, but I could see us optimizing this down the road.
