### ISSUE TITLE
500 while navigating to the waypoint

### ISSUE THREAD

**Issue by SanctusAnimus** [SpaceTradersAPI/api-docs#44]
Got it a few minutes ago when navigating REASON_ANCE-1 ship towards waypoint X1-DC54-43853Z
Ship was on full fuel (1200 / 1200), in orbit of X1-DC54-89945X

Sadly since it happened in the strategy automation, don't have any extra info to add

**Comment by space-admiral** [comment]
Awesome thanks for the ping! We'll check our logs and see if this can be patched. If you find this happening consistently, please feel free to ping here again and we can re-open the issue.
