### ISSUE TITLE
Inconsistency in OpenAPI spec

### ISSUE THREAD

**Issue by Heysem** [SpaceTradersAPI/api-docs#50]
Hello,

I noticed an inconsistency between 2 endpoints when generating an openapi client. 
The endpoints in question are both POST request and require no body to be sent. 
The first one:
/my/ships/{shipSymbol}/dock
Has no "requestBody" defined in the openAPI spec

However the second one:
"/my/ships/{shipSymbol}/negotiate/contract"

Requires an empty requestBody:
`"requestBody": {
          "content": {
            "application/json": {
              "schema": {}
            }
          }
        }`
https://github.com/SpaceTradersAPI/api-docs/blob/main/reference/SpaceTraders.json#L2770

Wouldn't it make more sense to remove the "requestBody" from the latter endpoint as well?

**Comment by space-admiral** [comment]
Absolutely! Thanks for catching this. Going to push a fix now.
