### ISSUE TITLE
Better Dynamic Respone Generation

### ISSUE THREAD

**Issue by arihant2math** [SpaceTradersAPI/api-docs#52]
[Link](https://docs.stoplight.io/docs/prism/9528b5a8272c0-dynamic-response-generation-with-faker)
So stoplight supports faker, which is immensely useful when writing sanity testing my sdk, as I can do it without having to go through the mess of setting up a secret for CI/CD or worrying about not being able to perform an action because I don't have the actual capability. However, I am unable to test waypoint symbols because, well, I parse them. So it would be cool if the dynamic response generation for waypoints could be either locked to a singular waypoint or set to a random list of them.

**Comment by space-admiral** [comment]
Ah yes that does sound helpful! Do you want to submit a PR for what this might look like? I don't see any issues with merging in a PR that helps improve the faker generated data.
