### ISSUE TITLE
Status API resetDate description

### ISSUE THREAD

**Issue by yamin8000** [SpaceTradersAPI/api-docs#55]
According to [docs](https://spacetraders.stoplight.io/docs/spacetraders/7534550e1ba52-get-status) resetDate is described as `The date and time when the game server was last reset.`, however, it only contains the date.  
resetDate is described the same but it's an instant instead of date and time.

**Comment by TruePikachu** [comment]
I'm also requesting this. Having the time of reset permits more flexibility in client design, especially considering that the current implementation will not disambiguate game sessions if the server had to be reset multiple times on the same date.

**Comment by space-admiral** [comment]
Thanks for reporting this - we won't be doing full server resets more than once on a day - and likely less frequently than the current once a week. I'll update the description to remove the time portion.
