### ISSUE TITLE
Duplicate "markets" Tags

### ISSUE THREAD

**Issue by rayliuca** [SpaceTradersAPI/api-docs#6]
https://github.com/SpaceTradersAPI/api-docs/blob/03052562d6d19a635c37de8eeb66514544157ab2/reference/SpaceTraders.yaml#L2971 is a duplicate of https://github.com/SpaceTradersAPI/api-docs/blob/03052562d6d19a635c37de8eeb66514544157ab2/reference/SpaceTraders.yaml#L2950

The second markets tag on line 2971 was introduced in commit b27949b. I would recommend removing one of them

Cheers,

**Comment by crisman** [comment]
Fixed in with move to `SpaceTraders.json` in commit eea39e49c0da18eeb0f134328bb889e5ceff8f87
