### ISSUE TITLE
/game/loans missing from SpaceTraders.json

### ISSUE THREAD

**Issue by bakerbrandond** [SpaceTradersAPI/api-docs#63]

**Comment by space-admiral** [comment]
Thanks for reporting this - I think you're referencing V1 of the API but these docs are for V2. There is no OpenAPI specification for the v1 of the API.

**Comment by bakerbrandond** [comment]
> Thanks for reporting this - I think you're referencing V1 of the API but these docs are for V2. There is no OpenAPI specification for the v1 of the API.

Did you mean there is no OpenAPI spec for the V2 spec? If that is the case is there an ETA for one?
