### ISSUE TITLE
contract fulfillment endpoint is not documented

### ISSUE THREAD

**Issue by dmitrij-schmidt** [SpaceTradersAPI/api-docs#7]
Contract fulfillment endpoint `/my/contracts/{contractId}/fulfill` is mentioned in [agent creation docs](https://spacetraders.stoplight.io/docs/spacetraders/adb4595a7bf6e-register-new-agent) but it is not explicitly mentioned in "contracts" section of the docs

**Comment by crisman** [comment]
Fixed in commit 8d3b4e5a0f3b3ebb24b6e6b90f469884dd639123
