### ISSUE TITLE
Waypoint filter incorrect spec

### ISSUE THREAD

**Issue by whyando** [SpaceTradersAPI/api-docs#81]
on /systems/{systemSymbol}/waypoints the spec reads as follows:
```
{
    "description": "Filter waypoints by one or more traits.",
    "in": "query",
    "name": "traits",
    "schema": {
        "oneOf": [
            {
                "$ref": "#/components/schemas/WaypointTrait"
            },
            {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/WaypointTrait"
                }
            }
        ]
    }
}
```
however this means putting a `#/components/schemas/WaypointTrait` in the query path

but WaypointTrait is a type object! with 3 required properties: symbol, name, description

obviously this is not the intent of the spec

impact:
1. all generated code will use this endpoint incorrectly
2. generators for compiled languages (eg rust) may generate code that doesn't compile, making the library unusable

**Comment by kjackson1998** [comment]
This was fixed. It needs to be published to stoplight.

https://github.com/SpaceTradersAPI/api-docs/pull/77
